import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidLibrary)
    alias(libs.plugins.jetbrains.kotlin.serialization)
}

// Generate BuildConfig for common code (configuration cache compatible)
abstract class GenerateBuildConfigTask : DefaultTask() {
    @get:Input
    abstract val useProduction: Property<Boolean>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val dir = outputDir.get().asFile.resolve("com/janusleaf/app")
        dir.mkdirs()
        val isProd = useProduction.get()
        dir.resolve("JanusLeafBuildConfig.kt").writeText(
            """
            package com.janusleaf.app

            /**
             * Build-time configuration.
             * Generated by Gradle - DO NOT EDIT MANUALLY.
             *
             * Build command used:
             *   Production: ./gradlew build -PuseProduction=true
             *   Development: ./gradlew build
             */
            object JanusLeafBuildConfig {
                const val USE_PRODUCTION: Boolean = $isProd
            }
            """.trimIndent()
        )

        println("\uD83D\uDD27 BuildConfig generated: USE_PRODUCTION = $isProd")
    }
}

val generateBuildConfig by tasks.registering(GenerateBuildConfigTask::class) {
    useProduction.set((project.findProperty("useProduction") as? String)?.toBoolean() ?: false)
    outputDir.set(layout.buildDirectory.dir("generated/source/buildConfig/commonMain/kotlin"))
}

kotlin {
    androidTarget {
        @OptIn(ExperimentalKotlinGradlePluginApi::class)
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "Shared"
            isStatic = true
        }
    }

    sourceSets {
        commonMain {
            // Include generated BuildConfig
            kotlin.srcDir(layout.buildDirectory.dir("generated/source/buildConfig/commonMain/kotlin"))

            dependencies {
                // Ktor - Networking
                api(libs.ktor.client.core)
                implementation(libs.ktor.client.content.negotiation)
                implementation(libs.ktor.client.logging)
                implementation(libs.ktor.serialization.kotlinx.json)

                // Kotlinx
                api(libs.kotlinx.coroutines.core)
                api(libs.kotlinx.serialization.json)
                api(libs.kotlinx.datetime)

                // DI
                api(libs.koin.core)

                // Logging
                api(libs.napier)
            }
        }

        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }

        androidMain.dependencies {
            implementation(libs.androidx.security.crypto)
            implementation(libs.kotlinx.coroutines.android)
            implementation(libs.ktor.client.okhttp)
            implementation(libs.koin.android)
        }

        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
    }
}

// Ensure BuildConfig is generated before compilation
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    dependsOn(generateBuildConfig)
}

tasks.matching { it.name.contains("compile") && it.name.contains("Kotlin") }.configureEach {
    dependsOn(generateBuildConfig)
}

android {
    namespace = "com.janusleaf.app.shared"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        minSdk = libs.versions.android.minSdk.get().toInt()
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}
